"""Backend-neutral navigation capability contracts."""

from .base import (
    NavigationClient,
    AbsoluteNavigationGoal,
    LocalizationState,
    LocalizationStatus,
    MapIdentity,
    NavigationError,
    NavigationGoalHandle,
    NavigationPose,
    NavigationState,
    NavigationStatus,
    NavigationUnavailableError,
    RelativeNavigationGoal,
)
from .fake import FakeNavigationClient
from .direct_go2 import DirectGo2NavigationClient
from .native_go2 import NativeGo2NavigationClient
from .grid import OccupancyGrid2D, costmap_from_pointcloud, with_obstacle_distance_costs
from .planner import (
    astar_path, find_nearest_safe_goal, path_collision_fraction,
    path_corridor_cells, path_minimum_clearance_m,
)
from .map_store import NativeMapIdentity, SparseVoxelMap
from .relocalization import (
    RelocalizationResult,
    merge_local_observation,
    relocalize_global,
    relocalize_with_initial,
)
from .frontier import FrontierGoal, find_frontier_goals
from .patrol import (
    PatrolStrategy, VisitationHistory, create_patrol_route, evaluate_patrol_route,
)
from .diagnostics import (
    NavigationTraceSummary,
    NavigationTraceWriter,
    NavigationTrajectoryMetrics,
    build_navigation_report,
    load_navigation_trace,
    navigation_trajectory_metrics,
    summarize_navigation_trace,
)
from .exploration import (
    ExplorationResult,
    ExplorationStopReason,
    FrontierExplorationController,
    evaluate_exploration_trace,
)
from .patrol_controller import (
    PatrolController, PatrolExecutionResult, evaluate_patrol_trace,
)
from .visual_navigation import (
    CameraIntrinsics,
    VisualServoCommand,
    bbox_to_relative_goal,
    compute_visual_servo,
    compute_visual_servo_3d,
    detection_bbox_to_pixels,
    detection_label_matches,
    robust_target_from_points,
)
from .visual_controller import (
    ContinuousVisualServoController,
    VisualServoResult,
    VisualTargetObservation,
    evaluate_visual_servo_trace,
)
from .pose_graph import (
    PlanarPose,
    PlanarPoseGraph,
    LoopVerificationResult,
    OnlinePoseGraphTracker,
    PoseGraphTrackerConfig,
    PoseGraphTrackerUpdate,
    PoseGraphConstraint,
    PoseGraphKeyframe,
    PoseGraphResult,
    compose_pose,
    inverse_pose,
    relative_pose,
    verify_loop_constraint,
)
from .motion_safety import LinearVelocityRampLimiter, NavigationMotionSafetySignal
from .terrain3d import (
    MultiLevelTerrainPlanner,
    RollingTerrainMap,
    SurfaceNode,
    SurfacePath,
    TerrainFrontierGoal,
    TerrainPlanState,
    TerrainPlanningBudgetExceeded,
    TerrainPlannerConfig,
    TerrainMapConfig,
    TerrainRegion,
    build_surface_graph,
    plan_surface_path,
)
from .terrain_controller import (
    TerrainExecutionResult, TerrainPathController, evaluate_terrain_execution_trace,
)
from .terrain_exploration import (
    TerrainExplorationResult, TerrainFrontierExplorationController,
    evaluate_terrain_exploration_trace,
)
from .topology import TopologyGraph, TopologyLandmark, TopologyNode
from .replay import (
    NavigationReplayFrame,
    NavigationReplayWriter,
    evaluate_replay_planning,
    load_navigation_replay,
)
from .sensors import (
    NavigationSensorProvider,
    NavigationSensorSnapshot,
    UnitreeNavigationSensorProvider,
)
from .nav2 import (
    Nav2Bridge,
    Nav2GoalSnapshot,
    Nav2GoalSubmission,
    Nav2NavigationClient,
    RclpyNav2Bridge,
    create_nav2_navigation_client,
)

__all__ = [
    "FakeNavigationClient",
    "DirectGo2NavigationClient",
    "NativeGo2NavigationClient",
    "OccupancyGrid2D",
    "costmap_from_pointcloud",
    "with_obstacle_distance_costs",
    "astar_path",
    "find_nearest_safe_goal",
    "path_minimum_clearance_m",
    "path_corridor_cells",
    "path_collision_fraction",
    "NativeMapIdentity",
    "SparseVoxelMap",
    "RelocalizationResult",
    "merge_local_observation",
    "relocalize_global",
    "relocalize_with_initial",
    "FrontierGoal",
    "find_frontier_goals",
    "PatrolStrategy",
    "VisitationHistory",
    "create_patrol_route",
    "evaluate_patrol_route",
    "NavigationTraceSummary",
    "NavigationTraceWriter",
    "NavigationTrajectoryMetrics",
    "navigation_trajectory_metrics",
    "build_navigation_report",
    "load_navigation_trace",
    "summarize_navigation_trace",
    "ExplorationResult",
    "ExplorationStopReason",
    "FrontierExplorationController",
    "evaluate_exploration_trace",
    "PatrolController",
    "PatrolExecutionResult",
    "evaluate_patrol_trace",
    "CameraIntrinsics",
    "VisualServoCommand",
    "bbox_to_relative_goal",
    "compute_visual_servo",
    "compute_visual_servo_3d",
    "detection_bbox_to_pixels",
    "detection_label_matches",
    "robust_target_from_points",
    "ContinuousVisualServoController",
    "VisualServoResult",
    "VisualTargetObservation",
    "evaluate_visual_servo_trace",
    "PlanarPose",
    "PlanarPoseGraph",
    "LoopVerificationResult",
    "OnlinePoseGraphTracker",
    "PoseGraphTrackerConfig",
    "PoseGraphTrackerUpdate",
    "PoseGraphConstraint",
    "PoseGraphKeyframe",
    "PoseGraphResult",
    "compose_pose",
    "inverse_pose",
    "relative_pose",
    "verify_loop_constraint",
    "LinearVelocityRampLimiter",
    "NavigationMotionSafetySignal",
    "SurfaceNode",
    "SurfacePath",
    "TerrainFrontierGoal",
    "TerrainPlannerConfig",
    "TerrainRegion",
    "TerrainPlanState",
    "TerrainPlanningBudgetExceeded",
    "MultiLevelTerrainPlanner",
    "TerrainMapConfig",
    "RollingTerrainMap",
    "TerrainExecutionResult",
    "TerrainPathController",
    "evaluate_terrain_execution_trace",
    "TerrainExplorationResult",
    "TerrainFrontierExplorationController",
    "evaluate_terrain_exploration_trace",
    "TopologyGraph",
    "TopologyLandmark",
    "TopologyNode",
    "build_surface_graph",
    "plan_surface_path",
    "NavigationReplayFrame",
    "NavigationReplayWriter",
    "evaluate_replay_planning",
    "load_navigation_replay",
    "NavigationClient",
    "AbsoluteNavigationGoal",
    "LocalizationState",
    "LocalizationStatus",
    "MapIdentity",
    "NavigationError",
    "NavigationGoalHandle",
    "NavigationPose",
    "NavigationState",
    "NavigationStatus",
    "NavigationUnavailableError",
    "NavigationSensorProvider",
    "NavigationSensorSnapshot",
    "Nav2Bridge",
    "Nav2GoalSnapshot",
    "Nav2GoalSubmission",
    "Nav2NavigationClient",
    "RclpyNav2Bridge",
    "RelativeNavigationGoal",
    "UnitreeNavigationSensorProvider",
    "create_nav2_navigation_client",
]
